.TH DWM 1 dwm\-VERSION
.SH NAME
dwm \- dynamic window manager
.SH SYNOPSIS
.B dwm
.RB [ \-v ]
.SH DESCRIPTION
dwm is a dynamic window manager for X. It manages windows in tiled, monocle
and floating layouts. Either layout can be applied dynamically, optimising the
environment for the application in use and the task performed.
.P
In tiled layouts windows are managed in a master and stacking area. The master
area contains one window by default, and the stacking area contains all other
windows. The number of master area windows can be adjusted from zero to an
arbitrary number. Master and stack areas, as well as open windows belonging
to them can be moved or rotated around in any direction dynamically. In monocle
layout all windows are maximised to the screen size. In floating layout windows
can be resized and moved freely. Dialog windows are always managed floating,
regardless of the layout applied.
.P
Windows are grouped by tags. Each window can be tagged with one or multiple
tags. Selecting certain tags displays all windows with these tags.
.P
Each screen contains a small status bar which displays all available tags,
user@hostname, the title of the focused window, the layout, the keyboard layout,
easy access button to this manual, "pointer warp on focused" function
status/toggle button, "view on tag" function status/toggle button, "keyboard
lock" status/toggle button and the "power" button. A floating window is indicated
with an empty square and a maximised floating window is indicated with a filled
square before the windows title.  The selected tags are indicated with a
different color. The tags of the focused window are indicated with a filled square
in the top left corner.  The tags which are applied to one or more windows are
indicated with an empty square in the top left corner.
.P
Each screen contains a small (extra) status bar which displays text read from the
root window name property (xsetroot -name "text") and a built-in "system tray."
.P
dwm draws a small border around windows to indicate the focus/urgency state.
.SH OPTIONS
.TP
.B \-v
prints version information to standard output, then exits.
.SH USAGE (Keyboard)
.SS Main commands
.TP
.B WinKey\-Return
Start
.BR st(1).
.TP
.B WinKey\-Backspace
Spawn
.BR dmenu(1)
for launching other programs.
.TP
.B WinKey\-ESC
Kill the currently
.BR focused
window
.TP
.B WinKey\-Shift\-ESC
Kill all
.BR unfocused
windows on the focused screen
.TP
.B WinKey\-Control\-ESC
Open
.BR 'shutdown'
menu
.TP
.B WinKey\-Control\-Shift\-ESC
Kill
.BR dwm
.TP
.B WinKey\-Home
Toggle
.BR dwm
.BR keyboard
.BR lock
(disable all shortcuts except 'quit dwm' and 'toggle keyboard lock')
.SS Window functions
.TP
.B WinKey\-Space
Toggle focused window between
.BR tiled
and
.BR floating
state.
.TP
.B WinKey\-Shift\-f
Toggle focused window
.BR native
.BR fullscreen
mode if available
.TP
.B WinKey\-Control\-f
Force focused window into
.BR pseudo
.BR fullscreen
mode
.TP
.B WinKey\-j
Focus the 
.BR previous
window on the focused screen
.TP
.B WinKey\-Shift\-j
Push the focused window into the
.BR previous
spot on the focused screen
.TP
.B WinKey\-k
Focus the 
.BR next
window on the focused screen
.TP
.B WinKey\-Shift\-j
Push the focused window into the
.BR next
spot on the focused screen
.TP
.B WinKey\-q
Focus the
.BR last
.BR focused
.BR window
on the focused screen
.TP
.B WinKey\-Shift\-q
Push the focused window into the spot of the
.BR last
.BR focused
.BR window
on the focused screen
.TP
.B WinKey\-w
Focus the window in the
.BR first
spot
.TP
.B WinKey\-Shift\-w
Push the focused window into the 
.BR first
spot
.TP
.B WinKey\-a
Focus the window in the
.BR second
spot
.TP
.B WinKey\-Shift\-a
Push the focused window into the 
.BR second
spot
.TP
.B WinKey\-z
Focus the window in the
.BR third
spot
.TP
.B WinKey\-Shift\-z
Push the focused window into the 
.BR third
spot
.TP
.B WinKey\-x
Focus the window in the
.BR last
spot
.TP
.B WinKey\-Shift\-x
Push the focused window into the 
.BR last
spot
.TP
.B WinKey\-c
Toggle
.BR 'warp
.BR on
.BR focus' 
function (warps pointer to the center of the focused window when on)
.SS Layout functions
.TP
.B WinKey\-`
Switch to the
.BR last
used layout.
.TP
.B WinKey\-Shift\-`
Switch to
.BR next
layout
.TP
.B WinKey\-Control\-`
Switch to
.BR previous
layout
.TP
.B WinKey\-Shift\-Control\-f
Toggle
.BR monocle
layout
.SS Tiled layout manipulation functions
.TP
.B WinKey\-Shift\-n
Increase
.BR nmaster
by 1 in tiled layout
.TP
.B WinKey\-Control\-n
Decrease
.BR nmaster
by 1 in tiled layout
.TP
.B WinKey\-r
Move
.BR master
.BR area
around the screen in clockwise direction
.TP
.B WinKey\-Shift\-r
Toggle the alignment of windows in
.BR master
.BR area
between vertical and horizontal
.TP
.B WinKey\-Control\-r
Toggle the alignment of windows in
.BR stack
.BR area
between vertical and horizontal
.TP
.B WinKey\-Control\-Shift\-r
Execute all 3
.BR tiled
.BR layout
(listed above) manipulation functions at once
.TP
.B WinKey\-h
Decrease the size of the
.BR master
.BR area.
.TP
.B WinKey\-Shift\-h
Decrease the size of the windows in the
.BR master
.BR area.
.TP
.B WinKey\-Control\-h
Decrease the size of the windows in the
.BR stack
.BR area.
.TP
.B WinKey\-Control\-Shift\-h
Execute all 3 size
.BR decreasing
functions (listed above)
.TP
.B WinKey\-l
Increase the size of the
.BR master
.BR area.
.TP
.B WinKey\-Shift\-l
Increase the size of the windows in the
.BR master
.BR area.
.TP
.B WinKey\-Control\-l
Increase the size of the windows in the
.BR stack
.BR area.
.TP
.B WinKey\-Control\-Shift\-l
Execute all 3 size
.BR increasing
functions (listed above)
.SS Tag functions
.TP
.B WinKey\-[1..9]
Go to the 
.BR nth
tag
.TP
.B WinKey\-Shift\-[1..9]
Throw the focused window to 
.BR nth
tag
.TP
.B WinKey\-Control\-[1..9]
View/remove all windows from
.BR nth
tag
.TP
.B WinKey\-Control\-Shift\-[1..9]
Share all windows on current tag with
.BR nth
tag
.TP
.B WinKey\-0
View
.BR all
windows with
.BR all
tag.
.TP
.B WinKey\-Shift\-0
View the focused window on
.BR all
tags
.TP
.B WinKey\-Tab
Toggle to the
.BR last
selected tags
.TP
.B WinKey\-Shift\-Tab
Go to the tag on the
.BR left
of the currently selected
.TP
.B WinKey\-Control\-Tab
Go to the tag on the
.BR right
of the currently selected
.TP
.B WinKey\-v
Toggle
.BR 'view
.BR on
.BR tag' 
function (follow the window to the tag it was thrown to)
.SS Monitor functions
.TP
.B WinKey\-,
Focus
.BR previous
monitor
.TP
.B WinKey\-Shift\-,
Tag
.BR previous
monitor
.TP
.B WinKey\-.
Focus
.BR next
monitor
.TP
.B WinKey\-Shift\-.
Tag
.BR next
monitor
.SS Cosmetic functions
.TP
.B WinKey\-b
Toggle
.BR bars
on the selected screen
.TP
.B WinKey\-Shift\-b
Toggle
.BR main
.BR bar
on the selected screen
.TP
.B WinKey\-Control\-b
Toggle
.BR extra
.BR bar
on the selected screen
.TP
.B WinKey\-Control\-Shift\-b
Swap
.BR bar
positions
.TP
.B WinKey\-t
Toggle between
.BR tags
.BR appearances
on the selected screen
.TP
.B WinKey\-Shift\-t
Hide
.BR vacant
.BR tags
on the selected screen
.TP
.B WinKey\-Shift\-p
.BR Increase
window
.BR border
size on the selected screen
.TP
.B WinKey\-Control\-p
.BR Decrease
window
.BR border
size on the selected screen
.TP
.B WinKey\-Control\-Shift\-p
set window
.BR border
size to
.BR default
on the selected screen
.TP
.B WinKey\-i
Toggle
.BR gaps
in
.BR monocle
layout on the selected screen
.TP
.B WinKey\-Shift\-i
Increase size of the
.BR inner
.BR gaps
on the selected screen
.TP
.B WinKey\-Control\-i
Decrease size of the
.BR inner
.BR gaps
on the selected screen
.TP
.B WinKey\-Control\-Shift\-i
Set size of
.BR inner
.BR gaps
to 
.BR 0
on the selected screen
.TP
.B WinKey\-i
Toggle
.BR gaps
in
.BR tiled
layout when only 1 window is visible on the selected screen
.TP
.B WinKey\-Shift\-i
Increase size of the
.BR outer
.BR gaps
on the selected screen
.TP
.B WinKey\-Control\-i
Decrease size of the
.BR outer
.BR gaps
on the selected screen
.TP
.B WinKey\-Control\-Shift\-i
Set size of
.BR outer
.BR gaps
to 
.BR 0
on the selected screen



.SH USAGE (Mouse)

.SS Status bar
.TP
.B Button1
click on a tag label to display all windows with that tag, click on the layout
label toggles between tiled and floating layout.
.TP
.B Button3
click on a tag label adds/removes all windows with that tag to/from the view.
.TP
.B WinKey\-Button1
click on a tag label applies that tag to the focused window.
.TP
.B WinKey\-Button3
click on a tag label adds/removes that tag to/from the focused window.
.SS Mouse commands
.TP
.B WinKey\-Button1
Move focused window while dragging. Tiled windows will be toggled to the floating state.
.TP
.B WinKey\-Button2
Toggles focused window between floating and tiled state.
.TP
.B WinKey\-Button3
Resize focused window while dragging. Tiled windows will be toggled to the floating state.
.SH CUSTOMIZATION
dwm is customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH SEE ALSO
.BR dmenu (1),
.BR st (1)
.SH ISSUES
Java applications which use the XToolkit/XAWT backend may draw grey windows
only. The XToolkit/XAWT backend breaks ICCCM-compliance in recent JDK 1.5 and early
JDK 1.6 versions, because it assumes a reparenting window manager. Possible workarounds
are using JDK 1.4 (which doesn't contain the XToolkit/XAWT backend) or setting the
environment variable
.BR AWT_TOOLKIT=MToolkit
(to use the older Motif backend instead) or running
.B xprop -root -f _NET_WM_NAME 32a -set _NET_WM_NAME LG3D
or
.B wmname LG3D
(to pretend that a non-reparenting window manager is running that the
XToolkit/XAWT backend can recognize) or when using OpenJDK setting the environment variable
.BR _JAVA_AWT_WM_NONREPARENTING=1 .
.SH BUGS
Send all bug reports with a patch to hackers@suckless.org.
